import {
  Add,
  Announce,
  Article,
  Cart,
  Clock,
  Close,
  DocumentText,
  FormClose,
  FormDown,
  FormNext,
  FormPrevious,
  FormTrash,
  Home,
  Lock,
  MailOption,
  Menu,
  Plan,
  Run,
  Schedules,
  Transaction,
  User,
  UserAdd,
  Video,
  Workshop,
} from 'grommet-icons';

export {
  Add as AddIcon,
  Plan as CalendarIcon,
  Cart as CartIcon,
  Clock as ClockIcon,
  Close as CloseIcon,
  FormDown as DownIcon,
  MailOption as EmailIcon,
  Run as ExitIcon,
  FormClose as FormCloseIcon,
  Home as HomeIcon,
  Menu as MenuIcon,
  FormNext as NextIcon,
  Workshop as OpenSpaceIcon,
  Lock as PasswordIcon,
  FormPrevious as PreviousIcon,
  Schedules as ScheduleIcon,
  Announce as TalkIcon,
  Article as TextIcon,
  DocumentText as TextAreaIcon,
  Transaction as TransactionIcon,
  FormTrash as TrashIcon,
  User as UserIcon,
  UserAdd as UserAddIcon,
  Video as VideoIcon,
};
