import {
  Add,
  Announce,
  Article,
  Clock,
  DocumentText,
  FormClose,
  FormDown,
  FormNext,
  FormTrash,
  Home,
  Lock,
  MailOption,
  Menu,
  Plan,
  Run,
  Schedules,
  User,
  Video,
  Workshop,
} from 'grommet-icons';

export {
  Add as AddIcon,
  Plan as CalendarIcon,
  Clock as ClockIcon,
  FormDown as DownIcon,
  MailOption as EmailIcon,
  Run as ExitIcon,
  FormClose as FormCloseIcon,
  Home as HomeIcon,
  Menu as MenuIcon,
  FormNext as NextIcon,
  Workshop as OpenSpaceIcon,
  Lock as PasswordIcon,
  Schedules as ScheduleIcon,
  Announce as TalkIcon,
  Article as TextIcon,
  DocumentText as TextAreaIcon,
  FormTrash as TrashIcon,
  User as UserIcon,
  Video as VideoIcon,
};
