import {
  Add,
  Announce,
  Article,
  Cart,
  Clock,
  Close,
  DocumentText,
  FormClose,
  FormUp,
  FormDown,
  FormNext,
  FormPrevious,
  FormTrash,
  Home,
  Lock,
  MailOption,
  Menu,
  Plan,
  Run,
  Schedules,
  Transaction,
  User,
  UserAdd,
  Video,
  Workshop,
  Link,
  Unlock,
  StatusGoodSmall,
  Projects,
  FormPreviousLink,
  Edit,
  Favorite,
  Trash
} from 'grommet-icons';

export {
  Add as AddIcon,
  Plan as CalendarIcon,
  Cart as CartIcon,
  Clock as ClockIcon,
  Close as CloseIcon,
  FormDown as DownIcon,
  FormUp as UpIcon,
  MailOption as EmailIcon,
  Run as ExitIcon,
  FormClose as FormCloseIcon,
  Home as HomeIcon,
  Menu as MenuIcon,
  FormNext as NextIcon,
  Workshop as OpenSpaceIcon,
  Lock as PasswordIcon,
  FormPrevious as PreviousIcon,
  Schedules as ScheduleIcon,
  Announce as TalkIcon,
  Article as TextIcon,
  DocumentText as TextAreaIcon,
  Transaction as TransactionIcon,
  FormTrash as TrashIcon,
  Trash as DeleteIcon,
  User as UserIcon,
  UserAdd as UserAddIcon,
  Video as VideoIcon,
  Link as LinkIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  StatusGoodSmall as CircleIcon,
  Projects as TracksIcon,
  FormPreviousLink as PreviousLinkIcon,
  Edit as EditIcon,
  Favorite as VoteIcon,
};
